[package]
name = "haversine"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
rand = "0.9.2"
rand_chacha = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
simd-json = { version = "0.15.1", features = ["known-key"] }
